const MESSAGE_SEARCH_MIN_LENGTH = 2;
const MESSAGE_SEARCH_MAX_LENGTH = 100;
const MESSAGE_SEARCH_LIMIT = 20;

export {
  MESSAGE_SEARCH_LIMIT,
  MESSAGE_SEARCH_MAX_LENGTH,
  MESSAGE_SEARCH_MIN_LENGTH,
};
